name: MSBuild

on:
  push:
    branches: [ "main" ]
    
jobs:
  build: 
    permissions:
      contents: read
      
    runs-on: ubuntu-latest
    timeout-minutes: 1

    steps:
    - uses: actions/checkout@v4

    - name: Build
      run: |
        chmod +x build.sh
        ./build.sh

    - name: Upload client application
      uses: actions/upload-artifact@v4
      with:
        name: client
        path: executables/client

    - name: Build docker
      run: |
        cd docker
        docker build -f network_dockerfile --platform linux/amd64 -t network:image .
        docker build -f cache_dockerfile --platform linux/amd64 -t cache:image .
        docker images

    - name: Login to Container Registry
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Tag images
      run: | 
          docker tag network:image ilia56/network_image:latest
          docker tag cache:image ilia56/cache_image:latest
  
    - name: Push images to docker hub Container Registry
      run: | 
          docker push ilia56/network_image:latest
          docker push ilia56/cache_image:latest
